---
- name: nginx & wordpress & php74 & mysql
  hosts: nginx
  tasks:
  - name: nginx install
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - wget
      - yum-utils
      - epel-release
      - nginx
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

  - name: wordpress install
    get_url:
      url: https://ko.wordpress.org/wordpress-5.8.6-ko_KR.tar.gz
      dest: ./

  - name: unarchive wordpress
    unarchive:
      src: wordpress-5.8.6-ko_KR.tar.gz
      dest: ./
      remote_src: yes

  - name: wordpress directory all file copy to /usr/share/nginx/html
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: yes
    loop:
      - {src: './wordpress/', dest: '/usr/share/nginx/html/' }
      - {src: '/usr/share/nginx/html/wp-config-sample.php', dest: '/usr/share/nginx/html/wp-config.php' }

  - name: yum-config-manager config
    shell:
      yum-config-manager --enable remi-php74
  
  - name: php7.4 install
    yum:
       name: "{{ packages }}"
    vars:
        packages:
          - php
          - php-common
          - php-opcache
          - php-mcrypt
          - php-cli
          - php-gd
          - php-curl
          - php-mysqlnd
          - php-fpm

  - name: wp-config.php file change
    replace:
      path: /usr/share/nginx/html/wp-config.php
      regexp: "{{ item.src }}"
      replace: "{{ item.dest }}"
    loop:
      - {src: "database_name_here", dest: "wordpress" }
      - {src: "username_here", dest: "root" }
      - {src: "password_here", dest: "It12345@" }
      - {src: "localhost", dest: "10.0.0.4" }

  - name: replace /etc/php-fpm.d/www.conf
    replace:
       path: /etc/php-fpm.d/www.conf
       regexp: "{{ item.src }}"
       replace: "{{ item.dest }}"
    loop:
      - {src: 'apache', dest: 'nginx'}
      - {src: 'nobody', dest: 'nginx'}
      - {src: 'listen = 127.0.0.1:9000', dest: ';listen = 127.0.0.1:9000' }
      - {src: ';listen.owner = nginx', dest: 'listen.owner = nginx' }
      - {src: ';listen.group = nginx', dest: 'listen.group = nginx' }

  - name: blockinfile /etc/php-fpm.d/www.conf
    blockinfile:
      path: /etc/php-fpm.d/www.conf
      insertafter: ";listen = 127.0.0.1:9000"
      marker: "; {mark} ANSIBLE MANAGED BLOCK "
      block: |
        listen = /run/php-fpm/www.sock

   - name: blockinfile /etc/nginx/nginx.conf
    blockinfile:
      path: /etc/nginx/nginx.conf
      marker: "# {mark} ANSIBLE MANAGED BLOCK "
      insertafter: '^(\s+include+\s)/etc/nginx/default.d/* conf;'
      block: |
        #aa
               index       index.php;
               location ~\.php$ {
                   try_files $uri =404;
                   fastcgi_pass unix:/run/php-fpm/www.sock;
                   fastcgi_index   index.php;
                   fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                   include fastcgi_params;
        }
        
  - name: systemd start nginx & php-fpm
    systemd:
      name: "{{ item }}"
      state: started
    loop:
      - php-fpm
      - nginx

  - name: firewall open 80/tcp
    firewalld:
      port: 80/tcp
      permanent: yes
      immediate: yes
      state: enabled
