---
- name: user add
  hosts: test
  tasks:
  - name: add user a
    user:
      name: a
      update_password: always
      password: "{{ 'It1' | password_hash('sha512') }}"
  - name: cat /etc/passwd
    shell: 'cat /etc/passwd | tail -2'
  - name: cat /etc/shadow
    shell: 'cat /etc/shadow | tail -2'

