---
- name: apache web server install
  hosts: test
  tasks:
  - name: install apache httpd
    yum:
      name: httpd
      state: latest
  - name: httpd service started
    service:
      name: httpd
      state: started
  - name: firewall open port 80/tcp
    firewalld:
      port: 80/tcp
      state: enabled
  - name: copy index file to html directory
    copy:
      src: index.html
      dest: /var/www/html/index.html
