---
- name: wordpress install
  hosts: web1
  tasks:
  - name: install wget
    yum:
      name: wget
      state: latest
  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: get_url repogistory
    get_url:
      url: https://ko.wordpress.org/wordpress-5.8.6-ko_KR.tar.gz
      dest: /root
  - name: tar xvfz
    shell: "tar xvfz wordpress-5.8.6-ko_KR.tar.gz"
  - name: copy wordpress file
    shell: "cp -a wordpress/* /var/www/html"
  - name: cp wp-config.php
    shell: cp /var/www/html/{wp-config-sample.php,sp-config.php}
  - name: lineinfile
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^DirectoryIndex index.html'
      line: 'DirectoryIndex index.php'
  - name: epel-release
    yum:
      name:
      - epel-release
      - yum-utils
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      - php
      - php-common
      - php-opcache 
      - php-mcryp
      - php-cli
      - php-gd
      - php-curl
      - php-mysqlnd
      state: latest
  - name: remi-php74
    shell : "yum-config-manager --enable remi-php74"
  - name: lineinfile wp-config.php
    lineinfile:
      path: /var/www/html/wp-config.php
      regexp:
      - '^database_name_here'
      - '^username_here'
      - '^password_here'
      - '^localhost'
      line:
      - 'worepress'
      - 'root1'
      - 'It12345!'
      - ' '
  - name: httpd service started
    service:
      name: httpd
      state: started
  - name: firewalld open 60,22,3306
    firewalld:
      port:
      - 80/tcp
      - 22/tcp
      - 3306/tcp
      state: enalbed
